# Generated by Django 4.0.4 on 2022-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_delete_kardexmanager'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='kardex',
            field=models.ManyToManyField(blank=True, to='productos.kardex'),
        ),
    ]
