# Generated by Django 4.0.4 on 2022-07-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_kardex_producto'),
        ('carrito', '0003_rename_kardex_carritoitem_karde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='karde',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='kardee',
            field=models.ManyToManyField(blank=True, to='productos.kardex'),
        ),
    ]
