# Generated by Django 4.0.4 on 2022-07-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_carritoitem_karde_carritoitem_kardee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='kardee',
            new_name='karde',
        ),
    ]
