# Generated by Django 4.0.4 on 2022-07-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_remove_carritoitem_karde_carritoitem_kardex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='kardex',
        ),
    ]
