# Generated by Django 4.0.4 on 2022-07-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_carritoitem_kardex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='kardex',
            new_name='kardexob',
        ),
    ]
