# Generated by Django 4.0.4 on 2022-07-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0009_rename_kardex_carritoitem_kardexob'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
