# Generated by Django 4.0.6 on 2022-08-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_userperfil_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
