# Generated by Django 4.0.4 on 2022-07-30 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0009_alter_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_numero', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('direccion_linea_1', models.CharField(max_length=100)),
                ('direccion_linea_2', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('orden_descripcion', models.CharField(blank=True, max_length=100)),
                ('orden_total', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Nuevo', max_length=50)),
                ('ip', models.BooleanField(blank=True, max_length=20)),
                ('confirmacion_orden', models.BooleanField(default=False)),
                ('orden_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_actualizada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_id', models.CharField(max_length=100)),
                ('pagos_metodos', models.CharField(max_length=100)),
                ('monto_id', models.CharField(max_length=100)),
                ('estado_id', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto_precio', models.FloatField()),
                ('ordenado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.kardex')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes_de_compra.orden')),
                ('pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes_de_compra.pago')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='pagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_compra.pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
