# Generated by Django 4.0.6 on 2022-08-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_image'),
        ('ordenes_de_compra', '0002_rename_impuesto_orden_inpuesto_alter_orden_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproducto',
            name='kardex',
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='kardex',
            field=models.ManyToManyField(blank=True, to='productos.kardex'),
        ),
    ]
