# Generated by Django 4.0.6 on 2022-08-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_compra', '0003_remove_ordenproducto_kardex_ordenproducto_kardex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='estado_id',
            new_name='estado',
        ),
    ]
