# Generated by Django 4.0.6 on 2022-08-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_compra', '0004_rename_estado_id_pago_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='estado',
            new_name='status',
        ),
    ]
