# Generated by Django 4.0.6 on 2022-08-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_compra', '0005_rename_estado_pago_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='pagos_metodos',
            new_name='payment_method',
        ),
    ]
