# Generated by Django 4.0.4 on 2022-08-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_compra', '0006_rename_pagos_metodos_pago_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenproducto',
            old_name='producto_precio',
            new_name='precio',
        ),
    ]
