# Generated by Django 4.0.4 on 2022-06-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
