# Generated by Django 4.0.4 on 2022-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_kardex'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='kardex',
            name='kardex_categoria',
            field=models.CharField(choices=[('calidad', 'calidad'), ('cantidad', 'cantidad')], max_length=100),
        ),
    ]
