# Generated by Django 4.0.4 on 2022-07-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_delete_kardexmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
