# Generated by Django 4.0.4 on 2022-08-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0009_alter_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sujeto', models.CharField(blank=True, max_length=200)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('calificacion', models.FloatField()),
                ('ip', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_subido', models.DateTimeField(auto_now=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
