# Generated by Django 4.0.4 on 2022-08-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_revisioncalificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisioncalificacion',
            old_name='productos',
            new_name='producto',
        ),
    ]
