# Generated by Django 3.2 on 2022-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_rename_productos_revisioncalificacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
